// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0cBg9bT2KJOdAKY1LsMUukmd2qyNHZCQ',
    appId: '1:1061791817244:web:804d0bfadfef0fc02489d9',
    messagingSenderId: '1061791817244',
    projectId: 'unikwik-e28ac',
    authDomain: 'unikwik-e28ac.firebaseapp.com',
    databaseURL: 'https://unikwik-e28ac-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'unikwik-e28ac.appspot.com',
    measurementId: 'G-JSDLD03TJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdaJCVS8b5TMOweNZX01FE11REaqYDRyM',
    appId: '1:1061791817244:android:01405a615a611cf82489d9',
    messagingSenderId: '1061791817244',
    projectId: 'unikwik-e28ac',
    databaseURL: 'https://unikwik-e28ac-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'unikwik-e28ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe9qqMrG5nfqcBNsd33iYaxu_U6FQf-FA',
    appId: '1:1061791817244:ios:4817d4d1546569ec2489d9',
    messagingSenderId: '1061791817244',
    projectId: 'unikwik-e28ac',
    databaseURL: 'https://unikwik-e28ac-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'unikwik-e28ac.appspot.com',
    iosClientId: '1061791817244-mgmfohjugmv44dimr3ik856chs01807g.apps.googleusercontent.com',
    iosBundleId: 'com.example.unikwikApp',
  );
}
